using CefSharp;
using CefSharp.WinForms;
using DevExpress.XtraEditors;
using ITXCatalogueManager.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ITXCatalogueManager.Forms
{
    public partial class frm_Location : DevExpress.XtraEditors.XtraForm
    {


        public string lat;
        public string lon;
        public string urlb;
        public string data { get; set; }
        public string datac { get; set; }
        public string description { get; set;  }
        public frm_Location()
        {
            InitializeComponent();
            var settings = new CefSharp.WinForms.CefSettings();
            settings.LogSeverity = LogSeverity.Verbose;
            settings.CachePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CefSharp\\Cache");
           
            Cef.Initialize(settings);
            
            //chromiumWebBrowser1.InitializeLifetimeService();
            //lat = "+36.026453";
            //lon = "-102.08660";
            //urlb = "https://www.google.com/maps/@" + lat + "," + lon + ",17.75z";
            splashScreenManager2.ShowWaitForm();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_Entities.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_Cities.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_entitiesGrid.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            SDS_States.Fill();
            splashScreenManager2.CloseWaitForm();
            chromiumWebBrowser1.Load("https://www.google.com.mx/maps/");
           

        }

        public string dourl(string lat, string lon)
        {
            return "https://www.google.com/maps/@" + lat + "," + lon + ",17.75z/data=!3m1!1e3";
        }

        private void btn_Save_Click(object sender, EventArgs e)
        {
            if (dxValidationProvider1.Validate() ){
                NewEntity ne = new NewEntity();
                ne.Id_Location = Guid.Empty;
                ne.Id_EntityType = (Guid)lue_locationType.EditValue;
                ne.Id_City = (Guid)lue_City.EditValue;
                ne.Latitude = (float)Convert.ToDecimal(edt_Lat.Text.ToString().Trim());
                ne.Longitude = (float)Convert.ToDecimal(edt_Lon.Text.ToString().Trim());
                ne.description = edt_Description.Text;
                ne.coords = ne.Latitude.ToString("0.000000") + "°, " + ne.Longitude.ToString("0.000000") + "°";
                ne.URL = edt_URL.Text;
                ne.address = edt_address.Text;
                ne.ZIPcode = edt_zip.Text;
                ne.Status = true;
                SQLCon.SQLCon con = new SQLCon.SQLCon();
                toastNotificationsManager1.Notifications[0].Body=
                con.sendNewEntity(ne).Rows[0].ItemArray[1].ToString();
                toastNotificationsManager1.Notifications[0].Header = "";
                toastNotificationsManager1.ShowNotification(toastNotificationsManager1.Notifications[0]);
                lue_locationType.EditValue = null;
                lue_City.EditValue = null;
                lue_state.EditValue = null;
                edt_Description.EditValue = null;
                edt_zip.EditValue = null;
                edt_address.EditValue = null;
                edt_Lat.EditValue = edt_Lon.EditValue = null;
                edt_URL.EditValue = null;
            }

        }

        private void lue_state_EditValueChanged(object sender, EventArgs e)
        {
            SDS_Cities.ClearRows();
            DevExpress.DataAccess.Sql.QueryParameter qp = new DevExpress.DataAccess.Sql.QueryParameter();
            qp.Name = "@ID_State";
            qp.Type = typeof(Guid);
            qp.Value = lue_state.EditValue;
            SDS_Cities.Queries[0].Parameters.Clear();
            SDS_Cities.Queries[0].Parameters.Add(qp);
            splashScreenManager2.ShowWaitForm();
            SDS_Cities.Fill();
            splashScreenManager2.CloseWaitForm();
            lue_City.Text = null;
        }

        private void edt_Log_EditValueChanged(object sender, EventArgs e)
        {
            //edt_URL.Text = dourl(edt_Lat.Text,edt_Lon.Text);
        }

        private async void btn_preview_Click(object sender, EventArgs e)
        {
           //edt_URL.Text = chromiumWebBrowser1.Address.ToString();

            //Coordendas 
            /////////////////////////////
            try
            {
                //description
                string script = string.Format("document.getElementsByClassName('x3AX1-LfntMc-header-title-title gm2-headline-5')[0].innerText;");
                await chromiumWebBrowser1.EvaluateScriptAsync(script).ContinueWith(x =>
                {
                    var response = x.Result;
                    if (response.Success && response.Result != null)
                    {
                        data = response.Result.ToString();
                        //MessageBox.Show(data);
                        Console.WriteLine(1);


                    }
                });
            }
            catch { }

            
            try
            {
                //Clickderecho coordenadas  DONE
                string script = string.Format("document.getElementsByClassName('nbpPqf-menu-x3Eknd-text')[0].innerText;");
                await chromiumWebBrowser1.EvaluateScriptAsync(script).ContinueWith(x =>
                {
                    var response = x.Result;
                    if (response.Success && response.Result != null)
                    {
                        datac = response.Result.ToString();
                        //MessageBox.Show(data);
                        Console.WriteLine(1);


                    }
                });
            }
            catch { }
            ////////////////////////////////////////////////
            try
            {
                //coords on no location pin try0
                string script22 = string.Format("document.getElementsByClassName('x3AX1-LfntMc-header-title-VdSJob')[0].innerText;");
                await chromiumWebBrowser1.EvaluateScriptAsync(script22).ContinueWith(x =>
                {
                    var response = x.Result;

                    if (response.Success && response.Result != null)
                    {
                        if (datac == null || datac.ToString().Replace(" ", "") == "")
                        {
                            datac = response.Result.ToString();
                        }
                        //Console.WriteLine(response.Message);
                        ////MessageBox.Show(data);
                        //Console.WriteLine(datac);
                    }
                });
            
            }
            catch { }
            try
            {
                //coords on no location pin try1
                string script22 = string.Format("document.getElementsByClassName('x3AX1-LfntMc-header-title-VdSJob')[1].innerText;");
                await chromiumWebBrowser1.EvaluateScriptAsync(script22).ContinueWith(x =>
                {
                    var response = x.Result;

                    if (response.Success && response.Result != null)
                    {
                        if (datac == null || datac.ToString().Replace(" ", "") == "")
                        {
                            datac = response.Result.ToString();
                        }
                        //Console.WriteLine(response.Message);
                        ////MessageBox.Show(data);
                        //Console.WriteLine(datac);
                    }
                });

            }
            catch { }

            if (datac != null && datac.ToString().Replace(" ","")!="")
            {
                string[] a = datac.Split(',');
                edt_Lat.Text = a[0].ToString().Trim();
                edt_Lon.Text = a[1].ToString().Trim();
                edt_URL.Text = dourl(a[0].ToString().Trim(), a[1].ToString().Trim());
            }
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            /////tittle/description
            ///
            string datatitle="";
            try
            {
                //description on pin 
                string script2 = string.Format("document.getElementsByClassName('x3AX1-LfntMc-header-title-title gm2-headline-5')[0].innerText;");
                    //".getAttribute('class');");
                await chromiumWebBrowser1.EvaluateScriptAsync(script2).ContinueWith(x =>
                {
                    var response = x.Result;

                    if (response.Success && response.Result != null)
                    {
                        datatitle = response.Result.ToString();
                        //MessageBox.Show(data);
                        Console.WriteLine(datatitle);
                    }
                });
            }
            catch { }


            edt_Description.Text = datatitle.ToString();
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            /////adresss and zipcode (need pin)
            ///
            string dataaddress="";
            try
            {
                //on know location
                string script2 = string.Format("document.getElementsByClassName('RcCsl dqIYcf-RWgCYc-text w4vB1d C9yzub-TSZdd-on-hover-YuD1xf AG25L')[0].innerText;");
                await chromiumWebBrowser1.EvaluateScriptAsync(script2).ContinueWith(x =>
                {
                    var response = x.Result;

                    if (response.Success && response.Result != null)
                    {
                        dataaddress = response.Result.ToString();
                        //MessageBox.Show(data);
                        Console.WriteLine(dataaddress);
                    }
                });
            }
            catch {
                
            }
            if (dataaddress == "")
            {
                try
                {

                    string script2 = string.Format("document.getElementsByClassName('section-info gm2-body-2 section-info-hoverable')[0].innerText;");
                    await chromiumWebBrowser1.EvaluateScriptAsync(script2).ContinueWith(x =>
                    {
                        var response = x.Result;

                        if (response.Success && response.Result != null)
                        {
                            dataaddress = response.Result.ToString();
                            //MessageBox.Show(data);
                            Console.WriteLine(dataaddress);
                        }
                    });
                }
                catch { }
            }
            string address="";
            if (dataaddress != "")
            {
                string[] aa = dataaddress.Split(',');
                int ii = 1;
                foreach (string i in aa)
                {
                    int s= aa.Length;
                    if (s != ii)
                    {
                        address += i+", ";
                    }
                    ii+=1;
                }
                if (address != "")
                {
                    edt_address.Text = address.Substring(0, address.Length - 2);
                }
                string strNum = new string(address.Where(c => char.IsDigit(c)).Reverse().Take(5).Reverse().ToArray());
                edt_zip.Text = strNum;
            }

            //catch { }
            //if (data != null)
            //{
            //    string[] a = data.Split(',');
            //    edt_Lat.Text = a[0].ToString().Trim();
            //    edt_Lon.Text = a[1].ToString().Trim();
            //    edt_URL.Text = dourl(a[0].ToString().Trim(), a[1].ToString().Trim());
            //}

            //webBrowser1.Navigate(edt_URL.Text);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            SDS_entitiesGrid.Fill();
        }

        private void frm_Entity_FormClosing(object sender, FormClosingEventArgs e)
        {
            Cef.Shutdown();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            chromiumWebBrowser1.Refresh();
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }
    }
}